sudo: false

language: go

go:
  - 1.13.x
  - master

install: true

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.1
  - go get -u golang.org/x/lint/golint

script:
  - make lint
  - go test -v -race ./...  # Run all the tests with the race detector enabled

matrix:
  allow_failures:
    - go: master